[tool.black]
exclude = '''
/(
    \.git
  | _build
  | build
  | dist
  | env
  | venv
)/
'''
line-length = 110
target-version = ['py310']

[tool.pycln]
all = true

[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 110
multi_line_output = 3
use_parentheses = true

[tool.ruff]
line-length = 110
force-exclude = true
target-version = "py310"
[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    "W",
    # pyflakes
    "F",
    # flake8-bugbear
    "B",
    # flake8-commas
    "COM",
    # flake8-comprehensions
    "C4",
    # flake8-implicit-str-concat
    "ISC",
    # flake8-simplify
    "SIM101", "SIM109", "SIM117", "SIM118",
    "SIM2",
]
ignore = ["E501", "F403", "B023"]

[tool.mypy]
python_version = "3.10"
show_error_codes = true
pretty = true
warn_unused_configs = true

# strict_optional = true
ignore_missing_imports = true
allow_untyped_globals = false
check_untyped_defs = false
disallow_incomplete_defs = false
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
implicit_reexport = false
